######################## default configuration ####################
baseURL = "https://chismcreations.netlify.app"
languageCode = "en"
title = "Chism Creations"
theme = "hargo-hugo"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"


############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Products"
  weight = 1
  hasChildren = true
  
    [[menu.main]]
    parent = "Products"
    name = "Quiet Ears"
    url = "products/quiet-ears/"
    weight = 1

    [[menu.main]]
    parent = "Products"
    name = "Crochet"
    url = "products/crochet/"
    weight = 2

  [[menu.main]]
  name = "About"
  url = "blog/"
  weight = 2
  
  [[menu.main]]
  name = "FAQ"
  url = "faq/"
  weight = 3

  #[[menu.main]]
  #name = "Contact"
  #url = "contact/"
  #weight = 4

  ############# footer menu #############
  [[menu.footer]]
  name = "Quiet Ears"
  url = "quiet-ears/"
  weight = 1

  [[menu.footer]]
  name = "Crochet"
  url = "crochet/"
  weight = 2

  [[menu.footer]]
  name = "FAQ"
  url = "faq/"
  weight = 3

  [[menu.footer]]
  name = "Terms & Conditions"
  url = "terms-conditions/"
  weight = 4

  #[[menu.footer]]
  #name = "Contact"
  #url = "contact/"
  #weight = 5


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Greg Chism"
# Google Analitycs
googleAnalyticsID = "G-NEL6QWPGF7" # Your ID
# Contact Information
email = "chismcreations@gmail.com"
location = "Tucson, Arizona"
# copyright
copyright = "| Copyright &copy; 2023 Chism Creations All Rights Reserved |"
# Snipcart Credentials
snipcartApiKey = "NjMxMWEzNTItYmFjOS00ODFkLTg3M2UtNWE2OTlhZjM5ODZhNjM4MTA4MTI0Njk3NzY2MDMx"
currencySymbol = "$"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Social Site
  [[params.social]]
  icon = "ti-facebook"
  link = "https://www.facebook.com/ChismCreations"

  #[[params.social]]
  #icon = "ti-twitter-alt"
  #link = "#"

  #[[params.social]]
  #icon = "ti-youtube"
  #link = "#"

  [[params.social]]
  icon = "ti-instagram"
  link = "https://www.instagram.com/chismcreations/"

  [[params.social]]
  icon = "ti-wand"
  link = "https://linktr.ee/ChismCreations"

  #[[params.social]]
  #icon = "ti-pinterest"
  #link = "#"

  # Contact Form
  [params.contact]
  formAction = "#" # contact form works with formspree.io

#############################################################
# Imaging setup
#############################################################
[imaging]
  # Default resample filter used for resizing. Default is Box,
  # a simple and fast averaging filter appropriate for downscaling.
  # See https://github.com/disintegration/imaging
  resampleFilter = "lanczos"
  # Default JPEG quality setting. Default is 75.
  quality = 85
  # Anchor used when cropping pictures.
  # Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
  # Smart Cropping is content aware and tries to find the best crop for each image.
  # Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
  anchor = "smart"

[params.imaging]
  # xl, lg, md, sm and below
  sizes = ["825","610","510","450"]